baseURL = "https://oldfroth.frothlang.org/"
languageCode = "en-us"
title = "OldFroth"
relativeURLs = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokailight"
    lineNos = false
    noClasses = false

[params]
  description = "Archive of the original Froth language and documentation."
